data:
  raw_data_path: "./data/census.csv"
  clean_data_path: "./data/census_clean.csv"
  train:
    full_data_path : "./data/clean_train_data.csv"
    featurized_data_path: "./data/census_featurized_train.npy"
    label_data_path: "./data/census_label_train.npy"
  test:
    full_data_path : "./data/clean_test_data.csv"
    featurized_data_path: "./data/census_featurized_test.npy"
    label_data_path: "./data/census_label_test.npy"
process_data:
  cat_features: [
        "workclass",
        "education",
        "marital_status",
        "occupation",
        "relationship",
        "race",
        "sex",
        "native_country"]
  label: "salary"
  train_mode:
    train: true
    encoder : None
    label_bin : None
  interfence_mode: 
    train: false
    encoder : "./model/encoder.joblib"
    label_bin : "./model/labelbin.joblib"
model:
  model_path: "./model/model.joblib"
  model_scoring_path: "./model/slice_output.txt"
  random_state: 112233
  test_ratio: 0.2
  cv_splits: 10
  gdb_params:
    n_estimators: 100
    learning_rate: 0.05
    min_samples_split: 500
    min_samples_leaf: 50
    max_depth: 8


